### PR TITLE
Dumpling & Cheeseburger: Update 20-12-2024

### PR DESCRIPTION
**Pull request by Zed9K**

### CODE REVIEW

**Review by gwolf2u — CHANGES_REQUESTED** [review]
Remove beta build type from device.json and changelog

**Comment by Zed9K** [comment]
done.

**Review by gwolf2u — CHANGES_REQUESTED** [review]
change in changelog also

**Comment by Zed9K** [comment]
done ( and im sorry, im doing this from work and im barely focusing and im sorry for the way too many commits! )

**Review by gwolf2u — APPROVED** [review]

**Pull request merged**
