### PR TITLE
Update OrangeFox Recovery links

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gwolf2u** [comment]
guys please confirm

**Comment by ctrl07** [comment]
His links dead

**Comment by ghost** [comment]
> His links dead

Should be fixed

**Review by Mustang-ssc — APPROVED** [review]
Ok here

**Comment by ctrl07** [comment]
Looks good :)

**Comment by gwolf2u** [comment]
@Mangomanid consider squashing commits when merging multiple commits from one pull request
squshed here and force-pushed

**Comment by ctrl07** [comment]
Will keep in mind henceforth

**Comment by officialyash007** [comment]
All fine for violet
Me late sorry 😅

**Pull request merged**
