### PR TITLE
munch: 07/11/2022 update

### PR DESCRIPTION
**Pull request by akash07k**
Signed-off-by: Akash Kakkar <akash.galaxy07@gmail.com>

### CODE REVIEW

**Comment by gwolf2u** [comment]
Try keeping changelog with a nice description

**Comment by akash07k** [comment]
Sure bro, actually I provided changelog like this because I thought that it will give all insights to the users about the changes.
Will make them better from now :-)
> Try keeping changelog with a nice description

**Comment by gwolf2u** [comment]
Fact is that this changelog (raw format) is available on phone under crDroid settings - about - changelog, for whoever needs it
The one you write in ota, is available in app and on website

**Comment by akash07k** [comment]
Oh, ok, I'll take care :-) Wasn't aware about it actually. ❤️

**Pull request merged**
