### PR TITLE
ota: add support for Raphael

### PR DESCRIPTION
**Pull request by Ayushd70**
Signed-off-by: Ayush Dubey <ayushdubey70@gmail.com>

### CODE REVIEW

**Comment by Ayushd70** [comment]
@gwolf2u .

**Comment by gwolf2u** [comment]
please rebase as there are conflicts

**Comment by Ayushd70** [comment]
will fix it. It wasn't there while creating the pr

**Comment by Ayushd70** [comment]
@gwolf2u merge

**Review by gwolf2u — APPROVED** [review]

**Pull request merged**
